name: Deploy API server to Kubernetes Cluster

on:
  workflow_dispatch:

jobs:  
  deploy-api-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kubectl commands
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl get nodes
          kubectl delete secret exosphere-api-server-secrets --ignore-not-found
          kubectl create secret generic exosphere-api-server-secrets --from-literal=MONGO_URI=${{ secrets.API_SERVER_MONGO_URI }} --from-literal=MONGO_DATABASE_NAME=${{ secrets.API_SERVER_MONGO_DATABASE_NAME }} --from-literal=JWT_SECRET=${{ secrets.API_SERVER_JWT_SECRET }}
          kubectl apply -f ./k8s/
